version: '3' 
  # not mandatory since Docker-Compose 1.27+, but it's a good practice to specify the version

services:
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    build:  #path to build the image
      context: ./requirements/mariadb
      dockerfile:  Dockerfile
    expose:
           - 3306:3306 #expose the port 3306 to be connected outside the container, 3306 is the default port for mariadb
            #need to be checked if usefull or not
    restart: unless-stopped # always restart the container unless it's stopped by docker-compose stop or docker-compose down
    volumes: 
      - mariadb_volume:/var/lib/mysql #mount the volume mariadb_volume to /var/lib/mysql
    env_file: .env #load the environment variables from the .env file
    networks: 
      - inception #connect the container to the network inception
      # - = list of networks even only one is used
  
  wordpress:
    image: wordpress:latest #official image of wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile:  Dockerfile
    expose:
      - 9000:9000 #exposed for PHP-FPM with the nginx server communication
    restart: unless-stopped #on-failure could also be acceptable in this case but unless-stopped is more secure
    volumes:
      - wordpress_volume:/var/www/html # root directory where wordpress is installed
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb #wordpress gonna depend on mariadb so it's gonna wait for mariadb to be ready before starting
  
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile:  Dockerfile
    ports:
      - 443:443 #443 is the default port for HTTPS (80 for HTTP)
    restart: unless-stopped
    volumes:
      - wordpress_volume:/var/www/html
    env_file: .env
    networks:
      - inception
    depends_on:
      - wordpress #nginx gonna depend on wordpress so it's gonna wait for wordpress to be ready before starting

networks:
  inception: #create a network named inception
    driver: bridge #use the bridge driver, which isolates de containers from the host network, 
                   #with multiple services they can communicate with each other, possible to use 
                   #the service name as a hostname without knowing the IP address, services are accessible
                   #from outside the network

volumes:
  mariadb_volume: #create a volume named mariadb_volume used to store the data of the mariadb database outside the container
    driver: local # the volume is stored on the host machine (this computer)
    driver_opts: #driver options
      type: none # indicates that Docker should not create a new volume, but use an existing one
      o: bind # indicates that Docker has to do a bind mount, which means that the volume is mounted to a specific directory on the host machine
      device: /home/ageiser/data/mariadb # the path to the directory on the host machine where the volume is mounted

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ageiser/data/wordpress